server {
    listen 80;
    server_name briceno-mora.es www.briceno-mora.es;
    root /sites/briceno-mora.es;
    index index.html;

    add_header Cache-Control $cache_control always;
    add_header X-Site "briceno-mora.es" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
