server {
    listen 80;
    server_name briceno-online.com www.briceno-online.com;
    root /sites/briceno-online.com;
    index index.html;

    add_header Cache-Control $cache_control always;
    add_header X-Site "briceno-online.com" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
