server {
    listen 80;
    server_name jesusjbriceno.es www.jesusjbriceno.es;
    root /sites/jesusjbriceno.es;
    index index.html;

    add_header Cache-Control $cache_control always;
    add_header X-Site "jesusjbriceno.es" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
