user  nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - [$time_local] "$host" "$request" $status $body_bytes_sent';
    access_log /var/log/nginx/access.log main;

    sendfile      on;
    tcp_nopush    on;
    keepalive_timeout 65;
    server_tokens off;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    gzip_min_length 1024;

    # Cache larga para media estatica (videos, imagenes)
    map $sent_http_content_type $cache_control {
        default                    "no-cache";
        ~video/                    "public, max-age=2592000";
        ~image/                    "public, max-age=2592000";
        ~font/                     "public, max-age=2592000";
    }

    include /etc/nginx/conf.d/*.conf;
}
